#!/bin/bash
# ============================================================
# HERU.gg — Database Setup Script
# Guides you through running migrations on your Supabase project
# Usage: bash scripts/setup-db.sh
# ============================================================

echo "============================================="
echo "  HERU.gg — Supabase Database Setup"
echo "============================================="
echo ""
echo "STEP 1: Go to your Supabase dashboard:"
echo "  https://supabase.com → your project → SQL Editor"
echo ""
echo "STEP 2: Run these migration files IN ORDER"
echo "  (copy-paste each file's contents into the SQL editor and run):"
echo ""
echo "  1. supabase/migrations/100_core.sql"
echo "     → user_profiles, staff_access_keys, app_settings, games, badges"
echo ""
echo "  2. supabase/migrations/101_gamers.sql"
echo "     → gamer_profiles, teams, tournaments, matches, friendships, DMs"
echo ""
echo "  3. supabase/migrations/102_organizers.sql"
echo "     → organizer_profiles, verifications, deliverables, bills, orders"
echo ""
echo "  4. supabase/migrations/103_providers.sql"
echo "     → service_provider_profiles, services (9 categories), bookings, coaching, reviews"
echo ""
echo "  5. supabase/migrations/104_sponsors.sql"
echo "     → sponsor_profiles, subscriptions, packages, sponsorships, revenue_ledger"
echo ""
echo "  6. supabase/migrations/105_rls.sql"
echo "     → Row Level Security policies"
echo ""
echo "  7. supabase/migrations/106_schema_fixes.sql"
echo "     → participant_type fix, venue_address, roi_data, task_board, files columns"
echo ""
echo "STEP 3: Get your Service Role Key:"
echo "  Supabase dashboard → Settings → API → copy 'service_role' key (secret)"
echo "  Add it to backend/.env as SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "STEP 4: Create staff access key in Supabase SQL Editor:"
echo "  INSERT INTO staff_access_keys (access_key, staff_name, staff_email, is_active)"
echo "  VALUES ('HERU-STAFF-OMAR-2026', 'Omar', 'omarabdelgawad001@gmail.com', true);"
echo ""
echo "STEP 5: (Optional) Load demo data:"
echo "  supabase/seed/seed.sql"
echo ""
echo "STEP 6: Run the app locally:"
echo "  Terminal 1: npm run dev          (frontend → http://localhost:5173)"
echo "  Terminal 2: cd backend && npm start  (backend  → http://localhost:3001)"
echo ""
echo "  Staff login: http://localhost:5173/admin"
echo "    Email: omarabdelgawad001@gmail.com"
echo "    Key:   HERU-STAFF-OMAR-2026"
echo ""
echo "See SETUP.md for full local development guide."
echo "See DATABASE_MIGRATION.md for migrating to a different database."
echo ""
