#!/bin/bash
# HERU.gg Database Setup Script
# This script guides you through running migrations on your Supabase project

echo "============================================="
echo "HERU.gg — Supabase Database Setup"
echo "============================================="
echo ""
echo "Your Supabase project: https://utlxvkwdcpwvdnkthksk.supabase.co"
echo ""
echo "STEP 1: Go to your Supabase dashboard:"
echo "  https://utlxvkwdcpwvdnkthksk.supabase.co"
echo ""
echo "STEP 2: Click 'SQL Editor' in the left sidebar"
echo ""
echo "STEP 3: Run these files IN ORDER (copy-paste each into the SQL editor):"
echo "  1. supabase/migrations/001_initial_schema.sql  (creates 16 tables)"
echo "  2. supabase/migrations/002_rls_policies.sql    (sets up security)"
echo "  3. supabase/migrations/003_indexes.sql         (performance indexes)"
echo "  4. supabase/migrations/004_storage.sql         (file upload bucket)"
echo "  5. supabase/seed/seed.sql                      (demo data)"
echo ""
echo "STEP 4: Get your Service Role Key:"
echo "  Supabase dashboard → Settings → API → copy 'service_role' key"
echo "  Add it to backend/.env as SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "STEP 5: Run the app:"
echo "  Terminal 1: cd backend && npm install && npm run dev"
echo "  Terminal 2: npm install && npm run dev"
echo ""
echo "The app will be available at: http://localhost:5173"
echo ""
echo "Staff login: http://localhost:5173/admin"
echo "  Email: omarabdelgawad001@gmail.com"
echo "  Key:   HERU-STAFF-OMAR-2026"
echo ""
